#!/bin/bash

. /etc/rc.d/init.d/functions

prog=supervisord
#exec_pro=/usr/local/python2.7/bin/supervisord
exec_pro=/usr/bin/supervisord
pidfile=/tmp/supervisord.pid


start(){
       echo -n $"Starting $prog"
       daemon $exec_pro -c /etc/supervisord.conf --pidfile $pidfile
       [ -f $pidfile ] && success $"$prog startup" || failure $"$prog startup"
       echo 
}
stop(){
        echo -n $"Stopping $prog"
	[ -f $pidfile ] && killproc $prog || success $"$prog shutdown"
	echo 
}



case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    stop
    start
    ;;
    status)
    status $prog
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
esac


